### PR TITLE
Add prettier plugin for code formatting

### PR DESCRIPTION
**Pull request by hbruch**
This PR adds prettier maven plugin to pom.xml to support a standard code formatting.
Configuration is copied from https://github.com/entur/lamassu

### CODE REVIEW

**Comment by testower** [comment]
Thanks for this!

Please have a look at the profiles section of lamassu pom: https://github.com/entur/lamassu/blob/master/pom.xml#L294-L322 as well as the CI configs: https://github.com/entur/lamassu/blob/master/.circleci/config.yml#L47, https://github.com/entur/lamassu/blob/master/.circleci/config.yml#L91, https://github.com/entur/lamassu/blob/master/.github/workflows/ci.yml#L19, https://github.com/entur/lamassu/blob/master/.github/workflows/ci.yml#L36

**Comment by testower** [comment]
Actually, this project has no github workflows - which I need to fix 😇

**Comment by hbruch** [comment]
I added the profiles to pom.xml. Will you create circleci and ci config then?

**Comment by testower** [comment]
If you give me access to update this PR I can fix it

**Pull request merged**
